services: mongodb

language: php

php:
  - 7.3

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer --dev install

script: phpunit --coverage-text
